import test from 'node:test';
import assert from 'node:assert/strict';

test('invoice flow validates settings, escapes customer input, generates a PDF, and invalidates changed invoices',async()=>{
  const elements=new Map();
  function element(id){if(!elements.has(id))elements.set(id,{value:'',checked:false,disabled:true,handlers:{},addEventListener(name,handler){this.handlers[name]=handler;},scrollIntoView(){}});return elements.get(id);}
  const keys=['name','city','phone','email','address','ein','zelle','venmo','cashapp','paypal'];
  const inputs=Object.fromEntries(keys.map(key=>[key,{value:''}]));
  element('settings-form').elements={namedItem:key=>inputs[key]};
  let saved='';
  globalThis.localStorage={getItem:()=>null,setItem:(key,value)=>{saved=value;}};
  const drawnFonts=[],drawnText=[];
  const context={scale(){},fillRect(){},fillText(text){drawnFonts.push(this.font);drawnText.push(text);},beginPath(){},moveTo(){},lineTo(){},stroke(){},measureText:value=>({width:value.length*6})};
  globalThis.document={fonts:{load:async()=>[{}]},getElementById:element,createElement:()=>({getContext:()=>context,toDataURL:()=>`data:image/jpeg;base64,${Buffer.from([255,216,255,217]).toString('base64')}`})};
  let shared;
  Object.defineProperty(globalThis,'navigator',{configurable:true,value:{canShare:()=>true,share:async data=>{shared=data;}}});
  const fire=async(id,event)=>element(id).handlers[event]({preventDefault(){}});
  await import('./app.js');
  element('hours').value='3';element('customer').value='<img src=x onerror=alert(1)>\nExample customer';
  await fire('invoice-form','submit');
  assert.equal(element('settings-panel').open,true);
  assert.equal(element('save-pdf').disabled,true);
  inputs.name.value='Test business';inputs.zelle.value='Test payment';inputs.ein.value='Test identifier';
  await fire('settings-form','submit');
  assert.ok(saved.includes('Test business'));assert.ok(!saved.includes('Example customer'));
  element('number').value='SYHO-250101';element('date').value='2025-01-01';
  await fire('invoice-form','submit');
  assert.equal(element('save-pdf').disabled,false);
  assert.ok(element('invoice').innerHTML.includes('&lt;img'));
  assert.ok(!element('invoice').innerHTML.includes('Test identifier'));
  assert.ok(element('invoice').innerHTML.includes('01/06/2025'));
  assert.equal(element('estimate').textContent,'$300.00');
  assert.ok(drawnFonts.length>0 && drawnFonts.every(font=>font.endsWith('px Inter')));
  assert.ok(element('invoice').innerHTML.includes('Sing Your ❤️‍🔥 Out'));
  await fire('share','click');
  assert.equal(shared.files[0].name,'SYHO-250101.pdf');
  assert.equal(shared.files[0].type,'application/pdf');
  assert.ok((await shared.files[0].text()).startsWith('%PDF-1.4'));
  element('discount').value='50';await fire('invoice-form','input');
  assert.equal(element('save-pdf').disabled,true);
  await fire('invoice-form','submit');
  assert.equal(element('estimate').textContent,'$250.00');
  assert.ok(element('invoice').innerHTML.includes('Flat discount'));
  assert.ok(element('invoice').innerHTML.includes('$300.00'));
  assert.ok(drawnText.includes('Flat discount   −$50.00'));
  assert.ok(drawnText.includes('Total due   $250.00'));
  for(const invalid of ['-1','300.01','1.001']){
    element('discount').value=invalid;await fire('invoice-form','input');await fire('invoice-form','submit');
    assert.equal(element('save-pdf').disabled,true);
    assert.ok(element('status').textContent.includes('Enter a discount'));
  }
  element('discount').value='';await fire('invoice-form','input');await fire('invoice-form','submit');
  assert.equal(element('estimate').textContent,'$300.00');
  assert.ok(!element('invoice').innerHTML.includes('Flat discount'));
  element('include-ein').checked=true;await fire('invoice-form','input');
  assert.equal(element('save-pdf').disabled,true);
  await fire('invoice-form','submit');
  assert.ok(element('invoice').innerHTML.includes('EIN: Test identifier'));
  element('hours').value='2.5';await fire('invoice-form','input');await fire('invoice-form','submit');
  assert.equal(element('save-pdf').disabled,true);
  assert.ok(element('status').textContent.includes('whole hours'));
  element('hours').value='3';
  document.fonts.load=async()=>{throw new Error('Font unavailable');};
  await fire('invoice-form','submit');
  assert.equal(element('save-pdf').disabled,true);
  assert.equal(element('print').disabled,false);
  assert.ok(element('status').textContent.includes('PDF generation failed'));
  const pending=[];
  document.fonts.load=()=>new Promise(resolve=>pending.push(resolve));
  const generating=fire('invoice-form','submit');
  element('hours').value='4';await fire('invoice-form','input');
  pending.forEach(resolve=>resolve([{}]));await generating;
  assert.equal(element('save-pdf').disabled,true);
  assert.equal(element('estimate').textContent,'$400.00');
});
